@startuml


Title Change Branded Prescription

actor "Pia Peters" as PATIENT
actor "Dr. Durant" as GP
participant "Vault" as VAULT
actor "Pharmacist" as PHARM
actor "Dr. Omar" as GP2

    
    
    
    
    
group Initial Contact

PATIENT -> GP : Goes to appointment\n
VAULT -> GP : Get Patient's Medication\n[[ExampleScenario-example-1-scenario-resources.html#EB Empty Bundle]]
GP -> VAULT : Create new prescription\n[[ExampleScenario-example-1-scenario-resources.html#1-prescription Amlor Prescription]]
end
    
group Treatment resources Creation

VAULT -> VAULT : Create new treatment\n[[ExampleScenario-example-1-scenario-resources.html#1-treatment New Treatment]]
VAULT -> VAULT : Create new treatment Line\n[[ExampleScenario-example-1-scenario-resources.html#1-treatmentLine New Treatment Line]]
VAULT -> VAULT : Resource Linking\n[[ExampleScenario-example-1-scenario-resources.html#1-1-provenance Link Prescription and treatmentLine]]
end
    
group Dispense

VAULT -> PHARM : Get patient's Prescriptions\n[[ExampleScenario-example-1-scenario-resources.html#EB Empty Bundle]]
PHARM -> VAULT : Create new dispense\n[[ExampleScenario-example-1-scenario-resources.html#1-dispense Amlodipin Sandoz dispense]]
end
    
group Resource Linkage

VAULT -> VAULT : Resource Linking\n[[ExampleScenario-example-1-scenario-resources.html#1-2-provenance Link Dispense and treatmentLine]]
end
    
group Vizualization Data for physician

GP2 -> VAULT : Requiring Visualization\n
VAULT -> VAULT : Creating Visualization\n
VAULT -> GP2 : Displaying Visualization\n[[ExampleScenario-example-1-scenario-resources.html#1-summary-view Summary view for a Physician]]
end
    
group Vizualization Data for patient (scheduled Administrations)

PATIENT -> VAULT : Requiring Visualization\n
VAULT -> VAULT : Creating Visualization\n
VAULT -> PATIENT : Displaying Visualization\n[[ExampleScenario-example-1-scenario-resources.html#1-scheduled-view Scheduled Administrations view for a Patient]]
end
  

@enduml
